# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegandb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='vegandb_app.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(related_name='products', to='vegandb_app.Shop'),
        ),
    ]
