# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vegandb_app', '0002_auto_20171016_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
