# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vegandb_app', '0003_product_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contetnt', models.TextField()),
                ('sent', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.IntegerField(choices=[(1, 'Dania gotowe'), (2, 'Słodkie'), (3, 'Mrożonki'), (4, 'Na kanapki'), (5, 'Wegański Nabiał')], verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredients',
            field=models.ImageField(upload_to='media/', verbose_name='Skład'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='vegandb_app.Manufacturer', verbose_name='Producent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='media/', verbose_name='Zdjęcie produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(related_name='products', to='vegandb_app.Shop', verbose_name='Sklepy'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nazwa'),
        ),
    ]
