# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegandb_app', '0004_auto_20171023_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='contetnt',
            new_name='content',
        ),
    ]
